import { useNavigate } from "react-router-dom";

export default function Home() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[#F7F7F7] text-gray-900 font-sans selection:bg-[#E5F156] selection:text-black pb-12">
      
      {/* Playful & Clean Navbar */}
      <nav className="flex justify-between items-center max-w-7xl mx-auto pt-6 pb-6 px-4 md:px-8">
        <div className="flex items-center gap-2 cursor-pointer" onClick={() => navigate('/')}>
          {/* Minimalist Logo */}
          <div className="w-8 h-8 bg-black rounded-full flex items-center justify-center">
            <div className="w-3 h-3 bg-[#72D177] rounded-full animate-pulse"></div>
          </div>
          <span className="text-2xl font-extrabold tracking-tighter text-black">QUIZORA</span>
        </div>
        <div className="hidden md:flex items-center gap-8 text-sm font-bold text-black/70">
          <a href="#features" className="hover:text-black transition-colors">Product</a>
          <a href="#features" className="hover:text-black transition-colors">Tech Stack</a>
          <a href="https://github.com/shrey8250/quizora-ai" target="_blank" rel="noreferrer" className="hover:text-black transition-colors">GitHub</a>
        </div>
        <div>
           {/* Changed to "Host Login" to reduce redundancy with the hero button */}
           <button onClick={() => navigate('/admin')} className="px-6 py-2.5 border-2 border-black text-black font-bold rounded-full hover:bg-black hover:text-white transition-all text-sm">
            Host Login
          </button>
        </div>
      </nav>

      {/* Massive Green Hero Section */}
      <div className="max-w-[95%] md:max-w-7xl mx-auto bg-[#72D177] rounded-[2.5rem] p-8 md:p-16 lg:p-24 relative overflow-hidden shadow-sm">
        
        <div className="relative z-10 max-w-2xl">
          <div className="inline-flex items-center gap-2 bg-black/10 px-4 py-1.5 rounded-full font-bold text-black text-xs uppercase tracking-wide mb-6">
            <span className="w-2 h-2 bg-black rounded-full"></span>
            AI-Powered Multiplayer
          </div>
          
          <h1 className="text-6xl md:text-7xl lg:text-[5rem] font-bold text-black leading-[1.05] tracking-tight mb-6">
            Real-Time Quizzes,<br />Generated by AI.
          </h1>
          
          <p className="text-black/80 text-lg md:text-xl font-medium max-w-xl mb-10 leading-relaxed">
            Upload your study material, let our AI extract the knowledge, and instantly host a live multiplayer quiz with zero latency.
          </p>

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row gap-4">
            <button 
              onClick={() => navigate('/play')}
              className="bg-black text-white rounded-full px-8 py-4 font-bold text-lg hover:scale-105 transition-transform flex justify-center items-center gap-2"
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
                <path strokeLinecap="round" strokeLinejoin="round" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
                <path strokeLinecap="round" strokeLinejoin="round" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              Join a Game
            </button>
            <button 
              onClick={() => navigate('/admin')}
              className="bg-transparent border-2 border-black text-black rounded-full px-8 py-4 font-bold text-lg hover:bg-black hover:text-white transition-all text-center"
            >
              Create Quiz
            </button>
          </div>
        </div>

        {/* Playful Floating UI Elements (Right Side) */}
        <div className="hidden lg:flex absolute right-12 top-1/2 -translate-y-1/2 flex-col gap-4 z-0 pointer-events-none">
          <div className="bg-white px-6 py-3 rounded-full shadow-xl font-bold text-black flex items-center gap-3 transform rotate-3 scale-110">
            <span className="bg-black text-white w-7 h-7 flex justify-center items-center rounded-full text-sm">A</span> 
            What is the DOM?
          </div>
          <div className="bg-white px-6 py-3 rounded-full shadow-xl font-bold text-black flex items-center gap-3 transform -translate-x-12 -rotate-2">
            <span className="bg-black text-white w-7 h-7 flex justify-center items-center rounded-full text-sm">B</span> 
            WebSockets vs HTTP
          </div>
          <div className="bg-white px-6 py-3 rounded-full shadow-xl font-bold text-black flex items-center gap-3 transform translate-x-4 rotate-2">
            <span className="bg-black text-white w-7 h-7 flex justify-center items-center rounded-full text-sm">C</span> 
            O(n log n) Complexity
          </div>
          {/* Yellow Accent Badge */}
          <div className="bg-[#E5F156] w-32 h-32 rounded-[2rem] absolute -bottom-16 -right-8 -z-10 flex flex-col justify-center items-center shadow-lg rotate-12">
             <span className="text-3xl font-black block">⚡️</span>
             <span className="font-bold text-xs uppercase mt-1">Instant AI</span>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <section id="features" className="max-w-[95%] md:max-w-7xl mx-auto mt-12 mb-12">
        <div className="grid md:grid-cols-3 gap-6">
          
          {/* Feature 1 */}
          <div className="bg-white p-8 rounded-[2rem] shadow-sm border border-black/5 hover:-translate-y-1 transition-transform">
            <div className="w-14 h-14 rounded-full bg-black flex items-center justify-center mb-6">
                <svg className="w-6 h-6 text-[#72D177]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
              </svg>
            </div>
            <h3 className="text-2xl font-bold text-black mb-3 tracking-tight">AI Pipeline</h3>
            <p className="text-black/60 font-medium leading-relaxed">
              Drop a PDF to instantly generate context-aware questions. Built with <span className="font-bold text-black">LangChain, Gemini Embeddings, and Groq LLMs</span>.
            </p>
          </div>

          {/* Feature 2 */}
          <div className="bg-white p-8 rounded-[2rem] shadow-sm border border-black/5 hover:-translate-y-1 transition-transform">
            <div className="w-14 h-14 rounded-full bg-black flex items-center justify-center mb-6">
                <svg className="w-6 h-6 text-[#E5F156]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            <h3 className="text-2xl font-bold text-black mb-3 tracking-tight">WebSockets</h3>
            <p className="text-black/60 font-medium leading-relaxed">
              Custom <span className="font-bold text-black">Node.js/Express</span> implementation handling concurrent client connections, room states, and instant synchronization.
            </p>
          </div>

          {/* Feature 3 - FIXED: Now matches the white theme of the other cards */}
          <div className="bg-white p-8 rounded-[2rem] shadow-sm border border-black/5 hover:-translate-y-1 transition-transform">
            <div className="w-14 h-14 rounded-full bg-black flex items-center justify-center mb-6">
                <svg className="w-6 h-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4" />
              </svg>
            </div>
            <h3 className="text-2xl font-bold text-black mb-3 tracking-tight">Robust Scale</h3>
            <p className="text-black/60 font-medium leading-relaxed">
              Persistent storage using <span className="font-bold text-black">MongoDB</span>, coupled with <span className="font-bold text-black">Redis & BullMQ</span> for high-performance background tasks.
            </p>
          </div>

        </div>
      </section>

      {/* Simple Footer */}
      <footer className="max-w-7xl mx-auto px-8 pt-8 flex justify-between items-center text-black/40 font-bold text-sm">
        <p>&copy; {new Date().getFullYear()} QUIZORA AI. Built for the web.</p>
        <a href="https://github.com/shrey8250/quizora-ai" className="hover:text-black transition-colors">View Source</a>
      </footer>

    </div>
  );
}